### ISSUE TITLE
Adminauthorization does not work

### ISSUE THREAD

**Issue by devnes** [Skycoder42/QtAutoUpdater#2]
Qt 5.6:
MAC OSX El Capitan:
AutoUpdaterGui/adminauthorization_mac.cpp:75: Warning: 'AuthorizationExecuteWithPrivileges' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
    status = AuthorizationExecuteWithPrivileges(authorizationRef, utf8Program.data(),

![2016-05-11 01 19 22](https://cloud.githubusercontent.com/assets/5395316/15164280/7eea8178-1716-11e6-86b7-54d9fe420a82.png)

Windows 10:

![screenshot_4426](https://cloud.githubusercontent.com/assets/5395316/15164399/16e7d8b8-1717-11e6-9ab6-ebf4498f8b21.png)

What I do wrong? 
If on windows comment this string (screenshot) then compiling is fine.
OS X able to solve the problem by writing return false; in AdminAuthorization::executeAsAdmin as first line.

**Comment by Skycoder42** [comment]
The decrepated warning should not be a problem, because it still works (at least on my machine...) Both errors are linker errors.

If you build as static library, no linking is required, thus I did not add the references. If you want to create a dll (and I suppose thats what you are doing), just add the libraries for each platform you can find in the qtautoupdater.pri file. Those are:
https://github.com/Skycoder42/QtAutoUpdater/blob/master/qtautoupdater.pri#L8
https://github.com/Skycoder42/QtAutoUpdater/blob/master/qtautoupdater.pri#L37

**Comment by Skycoder42** [comment]
Was the Problem solved with this? If yes, I am going to close this issue.
