### ISSUE TITLE
Can't find MaintenanceTool path for Mac

### ISSUE THREAD

**Issue by IQ-raf** [Skycoder42/QtAutoUpdater#25]
When passing the maintenancetool path to 
`QtAutoupdater::UpdateController("path/maintenancetool.app", qApp)`
The application crashes when the update button is clicked.

It works fine on windows with the following:
`QtAutoupdater::UpdateController("path/maintenancetool.exe", qApp)`

What should the path be like on mac? I cannot find an example (but I might just be bad at searching)

**Comment by IQ-raf** [comment]
I have been debugging this issue more, and I set up 
`controller = new QtAutoupdater::UpdateController("path/maintenancetool.app", qApp)` 
correctly, but when I click on my update button which triggers : 
`controller->start(QtAutoupdater::UpdateController::ProgressLevel)`
the whole app crashes, 

again this works fine on windows but not on Mac.

I also make sure that `setDetaledUpdateInfo()` is set to `true`

**Comment by IQ-raf** [comment]
It still crashes when I use the `createUpdateAction()` method for your information (still on Mac)

**Comment by Skycoder42** [comment]
Please add the following line to your code and investiage the created path:
```
controller = new QtAutoupdater::UpdateController("path/maintenancetool.app", qApp)
qDebug() controller->maintenanceToolPath();
```
Check if the detected path is valid and does point to the primary executable within the app bundle. You can, for example, use the `file` command to verify this. Also try to start the returned path directly, e.g. from the console to see if that work. Report your results here, so we can find out what is going on.

Also, "the app crashes" is never useful. Try to start the application via the debugger and collect the stacktrace (and possible RAM state) of the crash. With that information, I can actually do something.

**Comment by IQ-raf** [comment]
The detected path is correct, so this is not the reason that it crashes like I initially thought.
this is the output of the qDebug()
`./maintenancetool.app/Contents/MacOS/maintenancetool`

here is the the stacktrace (I think this is what you want, if not let me know)
[stacktrace.txt](https://github.com/Skycoder42/QtAutoUpdater/files/3282229/stacktrace.txt)

I don't really know how/what you mean by the RAM state unfortunately.

Thank you for your help !

**Comment by Skycoder42** [comment]
I might have located the error, the taskbar in [updatecontroller.cpp#L172](https://github.com/Skycoder42/QtAutoUpdater/blob/master/src/autoupdatergui/updatecontroller.cpp#L172) is null, because you created the updater without a window. This is indeed a bug! I will implement a fix ASAP, so you can try out if that makes it work again.

**Comment by IQ-raf** [comment]
thanks a lot ! do you know an approximate timeline for this bug fix so I can my work, I love your library and I would hate to have to do a quick hackyfix/use something else.

also why does it work in windows even when the taskbar is null ?

**Comment by Skycoder42** [comment]
Please clone the latest master branch and build the library yourself to verify this actually fixed the issue. The next release will probably be shortly after Qt 5.13 gets released.

Regarding windows: Honestly, I have no clue. Either there is something separate going on, or I did not correctly identify the bug. That's why I need you to test it. I currently have no macOs system available, so I can't test it myself
