### ISSUE TITLE
updatescheduler.cpp maintenancetool path error

### ISSUE THREAD

**Issue by devnes** [Skycoder42/QtAutoUpdater#3]
File updatescheduler.cpp has error in line 7:
# define TOOL_PATH QStringLiteral("../../maintenancetool");

right for osx will be: 
# define TOOL_PATH QStringLiteral("../../../maintenancetool");

**Comment by Skycoder42** [comment]
It depends on how you are using it.

Package structure: `MyApp.app/Contents/MacOS/MyApp`

If I use the first one, the path will be `MyApp.app/maintenancetool`. This is what I think is right, because on OsX you have the `MyApp.app` as "stand alone app", thus everything it uses should be inside of the `.app` folder. But if you want to use another path, just use the constructor with your custom path.
