### ISSUE TITLE
Build for Qt LTS, and source code can't be built

### ISSUE THREAD

**Issue by abdullah-radwan** [Skycoder42/QtAutoUpdater#30]
Please provide builds for Qt LTS versions, or don't make the versions work only on the Qt release it's built on.

I tried to build the current master source on MinGW32 7.3 on Windows 10, but it always fails with over 40+ errors, all related to source code itself (functions that don't exist, files not being included correctly, etc). I want to use the latest release on my program, but I can't build it.

For now, please provide a MinGW32 build for Qt 5.12.4 and Qt 5.12.5.

**Comment by Skycoder42** [comment]
Sorry, but in order to be able to use the latest features of Qt, the current release will always work only for the latest Qt release. For the LTS versions of Qt, I do maintain the last version that worked on them and rebuild and re-release them via the [QtModules-LTS](https://github.com/Skycoder42/QtModules-LTS/releases) repository.

I can't support older versions, as some features in the current code rely on newer stuff, added in 5.13. You won't expect new features to be added to the Qt LTS, so why should this libraries "LTS" build have new features?

However, if you want, you can create your own fork and try to backport to 5.12. I would link you in the README and help with errors you have.
