### ISSUE TITLE
Can't use your code

### ISSUE THREAD

**Issue by tigranpetrosyan** [Skycoder42/QtAutoUpdater#4]
Hi Skycoder42,

I have connected your library to my project. but when I call your code (maintenancetool) it does not work. 

This is what I get:
Has updates: false 
Has errors: true 

Can you help me with this? Or can you let me know what the reason is that it won't allow me to call the code within the function? 

Inside my apps main tool the maintenancetoo manual code works correctly.

**Comment by Skycoder42** [comment]
Without more information I'm afraid I can't help you much. However, the following steps may help to identify the problem:

- Extended Error information. You can get it from the Updater. (If you're using the UpdateController, you can get a reference to the updater via `controller->updater();`
  - Use `Updater::exitedNormally` to find out, whether the maintenance tool crashed or not
  - `Updater::errorLog` will give you extended information about what went wrong
  - `Updater::exitCode` may be helpful too, but probably not, since it's almost always simply 1 if it failed.
- Try running the maintenancetool via the commandline using `maintenancetool --checkupdates`
- Make shure the maintenancetool path is correct, via `Updater::maintenanceToolPath`

**Important:** "Has Errors" is always true, if "Has Updates" is false. This is a problem I was not able to fix, because the maintenancetool returns an error, if no updates are available! If the maintenancetool exited normally and nothing but "no updates" can be found in the error log, it actually worked fine! If you're unsure, try to create an update, and in that case, it should work!

I hope this helps you to figure out what went wrong. If you're still stuck, post the result of the 3 functions (exitedNormally, errorLog and exitCode) here, and I may be able to help you further.

**Comment by Skycoder42** [comment]
Have I been able to help you? If yes, please close this issue :)
