### ISSUE TITLE
Please use Qt coding rules for better import of the library

### ISSUE THREAD

**Issue by zack-snyder** [Skycoder42/QtAutoUpdater#5]
That means an Qt include should go like:
```
#include <QtCore/QString>
```
instead of:
```
#include <QString>
```

use the macros: `Q_SIGNALS:`, `Q_SLOTS` instead of `signals` and `slots`

I would personally also don't user `qoverload` in order to be compatible with older Qt versions, e.g. 5.6

**Comment by Skycoder42** [comment]
If you want to, you can create a pull request with your suggested changes for the includes and macros. As for now, I personally don't think it's that important for most usecases. But since I am planning to release the updater as a Qt Module, it's something I would do then. However, it may take some time until that happens.

Regarding the `QOverload` - I don't give much about backwards compability. If there are new features, I use them. So `QOverload` will stay.
